### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Postgrex.Messages.decode_fields/1

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-devops#3]
![image](https://cloud.githubusercontent.com/assets/194400/26101763/39daba66-3a2a-11e7-9337-e7ca4c77d8f6.png)

```sh
11:20:21.091 [error] GenServer #PID<0.438.0> terminating
** (FunctionClauseError) no function clause matching in Postgrex.Messages.decode_fields/1
    (postgrex) lib/postgrex/messages.ex:339: Postgrex.Messages.decode_fields("")
    (postgrex) lib/postgrex/messages.ex:344: Postgrex.Messages.decode_fields/1
    (postgrex) lib/postgrex/messages.ex:344: Postgrex.Messages.decode_fields/1
    (postgrex) lib/postgrex/messages.ex:131: Postgrex.Messages.parse/3
    (postgrex) lib/postgrex/protocol.ex:1842: Postgrex.Protocol.msg_decode/1
    (postgrex) lib/postgrex/protocol.ex:1816: Postgrex.Protocol.msg_recv/3
    (postgrex) lib/postgrex/protocol.ex:560: Postgrex.Protocol.auth_recv/3
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
Last message: nil
```

**Comment by nelsonic** [comment]
The issue was "Enforce SSL" on Azure...
Discovered reading: https://github.com/flynn/flynn/issues/3531
